services:
  backend_db:
    image: postgres:18
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/lib/postgresql 
    environment:
      - POSTGRES_DB=thequad
      - POSTGRES_PASSWORD=fewtyr4329thequad
      - POSTGRES_USER=mashce

volumes:
  pg_db:


# postgres://mashce:fewtyr4329thequad@localhost:5432/thequad
