services:
  backend_db:
    image: postgres:18
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/lib/postgresql 
    environment:
      - POSTGRES_DB=thequad
      - POSTGRES_PASSWORD=thequad
      - POSTGRES_USER=founder

volumes:
  pg_db:


# postgres://founder:thequad12@localhost:5432/thequad
